package com.example.products

object ProductData {
    val productList = listOf(
        Product(1, "Nike Court Vision Alta","Zapatillas Mujer","Sube el listón con las Nike Court Vision Alta. El diseño moderno combina piel en la parte superior con la elevación perfecta debajo. El look de baloncesto elevado ofrece la máxima suavidad e incorpora una lengüeta ultrasuave.",89.99, R.drawable.court_vision_alta ),
        Product(2, "Nike Air Max Furyosa","Zapatillas Mujer - Hombre","Con un look inspirado en las zapatillas de running trepidantes de los 90, las Nike Air Max Furyosa aportan un nuevo y potente diseño a tu armario.La unidad Air apilada y con drop en el talón proporcionan una gran amortiguación.",119.99, R.drawable.air_max_furyosa ),
        Product(3, "Nike Court Legacy Lift","Zapatillas Hombre","Eleva tu estilo con las Court Legacy Lift. La mediasuela con plataforma supone una declaración audaz de intenciones, que se suma al diseño sencillo y fácil de combinar. No te preocupes: hemos mantenido el ajuste clásico de las Court que te encanta.",69.99, R.drawable.court_legacy_lift ),
        Product(4, "Nike Icon Classic SE","Sandalias Mujer","Esta versión con tiras de las clásicas AF1 es tan cómoda como tus zapatillas favoritas. Cuenta con tiras regulables para que puedas personalizar el ajuste sin renunciar a un look alegre. Te ofrecemos el estilo robusto que te gusta con la comodidad que deseas.",41.99, R.drawable.icon_classic_se ),
        Product(5, "Nike Lazer Low Platafom","Zapatillas Mujer","Alabadas por su simplicidad y comodidad clásicas, las Nike Blazer Low Platform elevan este icono del baloncesto. La mediasuela y la suela exterior con elevación te permiten pisar con seguridad, y la parte superior mantiene las proporciones que más te gustaban de las originales.",79.99, R.drawable.nike_lazer_low_plataform ),
        Product(6, "Nike Air Max Furyosa NRG","Zapatillas Mujer","Con un look atrevido inspirado en las zapatillas de running trepidantes de los 90, las Air Max Furyosa NRG aportan una nueva y potente voz al mundo de la moda y la comodidad. La unidad Nike Air apilada y con drop en el talón supone toda una declaración de amortiguación.",103.99, R.drawable.nike_air_max_furyosa_nrg ),
        Product(7, "Nike AirMax 95","Zapatillas Hombre","Inspirado en el cuerpo humano y en la estética deportiva de los 90, el característico diseño combina innovaciones técnicas con un estilo trepidante. Esta versión combina materiales híbridos y amortiguación Max Air visible para crear un look por capas con una comodidad increíble.",179.99, R.drawable.nike_air_max_95 ),
        Product(8, "Nike Air Force 1'07 LX","Zapatillas Hombre","Estas AF1 combinan distintas capas en tonos ashen slate, dark obsidian y pink blast en un modelo de piel flor y tela vaquera para dar un soplo de aire fresco a unas zapatillas urbanas nacidas del baloncesto.",119.99, R.drawable.nike_air_force_107_lx ),
        Product(9, "Nike Ja 2 Nightmare","Zapatillas Hombre","Ja se esfuerza por dar lo mejor de sí mismo cuando el partido está en juego. Por eso las Ja 2 tienen un diseño más ligero. Se combina con la amortiguación Air Zoom para mantener la frescura para mejorar. Y la tracción inspirada en los neumáticos del tractor le ayuda a cambiar de dirección con facilidad.",134.99, R.drawable.ja_2_nigthmare ),
        Product(10, "Nike Terrascout","Zapatillas Hombre","Las Nike Terrascout están listas para explorar nuevos caminos. Su bandeleta texturizada hace frente al barro y la humedad, mientras que el forro de felpa suave mantiene los pies cálidos y cómodos. Además, la suela exterior de goma resistente ofrece el agarre necesario para explorar nuevos terrenos.",84.99, R.drawable.nike_terrascout )
    )
}